### PR TITLE
put a space between the time and subject for short events

### PR DESCRIPTION
**Pull request by adamralph**
Currently short events have the time and subject squeezed right together, e.g.:

`15:00walk the dog`

This PR puts a space (margin) between them:

`15:00 walk the dog`

I chose 0.2em since it seems to look OK, and it's the "minimum" space width recommended at https://www.cs.tut.fi/~jkorpela/styles/spaces.html but there doesn't seem to be any definite info on this. Moreover, it tends to be font-dependent: http://tex.stackexchange.com/questions/19411/spaces-width-between-the-words

Perhaps it needs to be tweaked by measuring the size of a real space in the used font, or perhaps another approach is needed, to actually add a real space character.

### CODE REVIEW

**Comment by zowesiouff** [comment]
Good catch! FullCalendar uses an `:after` pseudo-element to insert a dash surrounded by nbsps: 

```
.fc-time-grid-event.fc-short .fc-time:after {
	content: "\000A0-\000A0"; /* seperate with a dash, wrapped in nbsp's */
}
```

 _this was removed when we first introduced time on the right, which then was reverted because of stacking issues mentioned in #17_ 

It's going to be slightly larger than `0.2rem` but gives a clearer separation imho + reduces Kin's divergence from FC.

**dash + nbsps**
dash + nbsps

**margin 0.2rem**
margin 0.2rem

Either solutions works for me, though maybe a nice middle ground could be to use an `:after` with a simple nbsp in it?

**Comment by adamralph** [comment]
I think :after with nbsp makes sense. After all, that's what the margin is
trying to emulate. I'll update the PR later today unless you fix it in the
meantime.

**Comment by adamralph** [comment]
@zowesiouff I pushed a commit to change it to nsbp in `::after`.

**Comment by adamralph** [comment]
...and another commit which actually works.

I can squash any or all of the commits if you want me to. Just let me know.

**Comment by zowesiouff** [comment]
... and it's live on kin.today.

I've put your account as a contributor for a couple of months, thanks for the PR Adam!

**Comment by adamralph** [comment]
Great, thank you @zowesiouff!

**Pull request merged**
